SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE analytics_events;
TRUNCATE TABLE analytics_funnel;
TRUNCATE TABLE analytics_page_views;
TRUNCATE TABLE analytics_sessions;

SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE analytics_sessions
  MODIFY first_visit_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY last_activity_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE analytics_page_views
  MODIFY entered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY left_at DATETIME NULL DEFAULT NULL,
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE analytics_events
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE analytics_funnel
  MODIFY visited_site_at DATETIME NULL DEFAULT NULL,
  MODIFY viewed_product_at DATETIME NULL DEFAULT NULL,
  MODIFY added_to_cart_at DATETIME NULL DEFAULT NULL,
  MODIFY started_checkout_at DATETIME NULL DEFAULT NULL,
  MODIFY filled_name_at DATETIME NULL DEFAULT NULL,
  MODIFY filled_phone_at DATETIME NULL DEFAULT NULL,
  MODIFY selected_delivery_at DATETIME NULL DEFAULT NULL,
  MODIFY filled_delivery_at DATETIME NULL DEFAULT NULL,
  MODIFY selected_payment_at DATETIME NULL DEFAULT NULL,
  MODIFY clicked_submit_at DATETIME NULL DEFAULT NULL,
  MODIFY completed_order_at DATETIME NULL DEFAULT NULL,
  MODIFY paid_order_at DATETIME NULL DEFAULT NULL,
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE orders
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

SHOW COLUMNS FROM analytics_sessions LIKE '%_at';
SHOW COLUMNS FROM orders LIKE 'created_at';
